import {
  composeSharedCriterion,
  sharedCriterionTemplates,
} from "./sharedCriteria";
import type {
  FacultyRubric,
  FacultyRubricCriterion,
  FacultyRubricEvaluationMode,
} from "./types";

type CriterionInput = Omit<FacultyRubricCriterion, "weight" | "critical"> &
  Partial<Pick<FacultyRubricCriterion, "weight" | "critical" | "provisionalWeight">>;

function criterion(input: CriterionInput): FacultyRubricCriterion {
  return {
    weight: input.expectation === "neutral" ? 0 : 1,
    critical: false,
    provisionalWeight: input.expectation !== "neutral" && input.weight === undefined,
    ...input,
  };
}

function shared(
  template: keyof typeof sharedCriterionTemplates,
  overrides: Parameters<typeof composeSharedCriterion>[1],
) {
  return composeSharedCriterion(sharedCriterionTemplates[template], overrides);
}

function unscoredShared(
  template: keyof typeof sharedCriterionTemplates,
  overrides: Parameters<typeof composeSharedCriterion>[1],
): FacultyRubricCriterion {
  return {
    ...composeSharedCriterion(sharedCriterionTemplates[template], overrides),
    expectation: "neutral",
    weight: 0,
    provisionalWeight: false,
  };
}

function finding({
  id,
  name,
  title,
  expectedValue = true,
  critical = false,
  legacyPatientChecklistIds,
  legacyClinicalChecklistIds,
  acceptedConcepts,
}: {
  id: string;
  name: string;
  title: string;
  expectedValue?: string | boolean | string[];
  critical?: boolean;
  legacyPatientChecklistIds?: string[];
  legacyClinicalChecklistIds?: string[];
  acceptedConcepts?: string[];
}) {
  return criterion({
    id,
    name,
    title,
    description: `Elicited the expected case finding: ${title}.`,
    competency: "clinical-findings",
    evaluationMode: "finding-elicitation",
    expectation: "required",
    source: "faculty-clinical-checklist",
    expectedValue,
    critical,
    acceptedConcepts,
    legacyPatientChecklistIds,
    legacyClinicalChecklistIds,
    reportLabel: title,
  });
}

function neutralFinding(id: string, name: string, title: string) {
  return criterion({
    id,
    name,
    title,
    description:
      "Unmarked faculty-source finding. Asking about it is allowed, but it is neutral for grading.",
    competency: "clinical-findings",
    evaluationMode: "case-state",
    expectation: "neutral",
    source: "faculty-clinical-checklist",
    expectedValue: false,
    critical: false,
    reportLabel: title,
  });
}

function interpretation({
  id,
  name,
  title,
  description,
  expectedValue,
  critical = false,
  legacyClinicalChecklistIds,
  evaluationMode = "clinical-statement",
  facultyNotes,
}: {
  id: string;
  name: string;
  title: string;
  description: string;
  expectedValue?: string | boolean | string[];
  critical?: boolean;
  legacyClinicalChecklistIds?: string[];
  evaluationMode?: FacultyRubricEvaluationMode;
  facultyNotes?: string;
}) {
  return criterion({
    id,
    name,
    title,
    description,
    competency: "clinical-interpretation",
    evaluationMode,
    expectation: "required",
    source: "faculty-clinical-checklist",
    expectedValue,
    critical,
    legacyClinicalChecklistIds,
    reportLabel: title,
    facultyNotes,
  });
}

function recommendation({
  id,
  name,
  title,
  description,
  critical = false,
  acceptedConcepts,
  legacyClinicalChecklistIds,
  expectedValue = true,
  facultyNotes,
}: {
  id: string;
  name: string;
  title: string;
  description: string;
  critical?: boolean;
  acceptedConcepts?: string[];
  legacyClinicalChecklistIds?: string[];
  expectedValue?: boolean;
  facultyNotes?: string;
}) {
  return criterion({
    id,
    name,
    title,
    description,
    competency: "management-planning",
    evaluationMode: "recommendation",
    expectation: "required",
    source: "faculty-clinical-checklist",
    acceptedConcepts,
    critical,
    legacyClinicalChecklistIds,
    reportLabel: title,
    expectedValue,
    facultyNotes,
  });
}

function reviewedAvailableExamination({
  id,
  legacyPatientChecklistIds = ["examination-findings"],
}: {
  id: string;
  legacyPatientChecklistIds?: string[];
}) {
  return criterion({
    id,
    name: "reviewed-available-examination-findings",
    title: "Reviewed Available Examination Findings",
    description:
      "Reviewed the structured examination media made available for this case.",
    competency: "examination",
    evaluationMode: "examination-action",
    expectation: "required",
    source: "legacy-checklist",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds,
    reportLabel: "Reviewed available examination findings",
  });
}

function recognizedExaminationFinding({
  id,
  name,
  title,
  acceptedConcepts,
  critical = false,
}: {
  id: string;
  name: string;
  title: string;
  acceptedConcepts: string[];
  critical?: boolean;
}) {
  return criterion({
    id,
    name,
    title,
    description: `Correctly identified the structured examination finding: ${title}. Opening an examination asset alone does not satisfy this criterion.`,
    competency: "examination",
    evaluationMode: "clinical-statement",
    expectation: "required",
    source: "faculty-clinical-checklist",
    acceptedConcepts,
    critical,
    reportLabel: title,
  });
}

function recognizedClinicalFinding({ id, name, title, acceptedConcepts, critical = false }: { id: string; name: string; title: string; acceptedConcepts: string[]; critical?: boolean }) {
  return criterion({
    id,
    name,
    title,
    description: `Correctly recognized the clinical finding: ${title}.`,
    competency: "clinical-findings",
    evaluationMode: "clinical-statement",
    expectation: "required",
    source: "faculty-clinical-checklist",
    acceptedConcepts,
    critical,
    reportLabel: title,
  });
}

const case01Criteria: FacultyRubricCriterion[] = [
  unscoredShared("askedAboutFever", { id: "C1-IG-001", weight: 0, critical: false, facultyNotes: "Unscored for the Case 1 emergency pathway per confirmed Phase 1 checklist review." }),
  unscoredShared("askedAboutPenicillinAllergy", { id: "C1-IG-002", weight: 0, critical: false, facultyNotes: "General medication and penicillin allergy questions are unscored for the Case 1 emergency pathway per confirmed Phase 1 checklist review." }),
  unscoredShared("askedAboutColdPain", { id: "C1-IG-003", weight: 0, critical: false, facultyNotes: "Unscored for Case 1 per confirmed Phase 1 checklist review." }),
  unscoredShared("askedAboutLingeringColdPain", { id: "C1-IG-004", weight: 0, critical: false, facultyNotes: "Unscored for Case 1 per confirmed Phase 1 checklist review." }),
  unscoredShared("askedAboutBitingPain", { id: "C1-IG-005", weight: 0, critical: false, facultyNotes: "Unscored for Case 1 per confirmed Phase 1 checklist review." }),
  unscoredShared("askedAboutHomeMedicationUse", { id: "C1-IG-006", weight: 0, critical: false, facultyNotes: "Unscored for Case 1 per confirmed Phase 1 checklist review." }),
  finding({
    id: "C1-IG-007",
    name: "asked-about-positional-breathing",
    title: "Asked About Positional Breathing Difficulty",
    critical: true,
    acceptedConcepts: ["breathing worse lying flat", "cannot lie flat", "supine dyspnea"],
  }),
  finding({
    id: "C1-IG-008",
    name: "asked-about-drooling",
    title: "Asked About Drooling",
    critical: true,
    acceptedConcepts: ["drooling", "difficulty handling secretions"],
  }),
  finding({
    id: "C1-IG-009",
    name: "asked-about-medical-conditions",
    title: "Asked About Relevant Medical Conditions",
    acceptedConcepts: ["diabetes", "hypertension", "medical conditions"],
    legacyPatientChecklistIds: ["medical-history"],
    legacyClinicalChecklistIds: ["clinical-4"],
  }),
  finding({
    id: "C1-IG-010",
    name: "asked-about-dental-source-and-progression",
    title: "Asked About Dental Source and Swelling Progression",
    acceptedConcepts: ["left mandibular molar", "swelling progression", "rapidly worsening swelling"],
    legacyClinicalChecklistIds: ["clinical-2"],
  }),
  finding({
    id: "C1-CF-001",
    name: "elicited-difficulty-breathing",
    title: "Elicited Difficulty Breathing",
    critical: true,
    legacyPatientChecklistIds: ["airway"],
    legacyClinicalChecklistIds: ["clinical-1"],
    acceptedConcepts: ["trouble breathing", "dyspnea", "airway symptoms"],
  }),
  finding({
    id: "C1-CF-002",
    name: "elicited-bilateral-submandibular-swelling",
    title: "Elicited Bilateral Submandibular Swelling",
    critical: true,
    legacyPatientChecklistIds: ["airway"],
    legacyClinicalChecklistIds: ["clinical-1"],
    acceptedConcepts: ["bilateral swelling", "submandibular swelling"],
  }),
  finding({
    id: "C1-CF-003",
    name: "elicited-difficulty-swallowing",
    title: "Elicited Difficulty Swallowing",
    critical: true,
    legacyPatientChecklistIds: ["airway"],
    legacyClinicalChecklistIds: ["clinical-1"],
    acceptedConcepts: ["dysphagia", "trouble swallowing", "painful swallowing"],
  }),
  finding({
    id: "C1-CF-004",
    name: "elicited-difficulty-speaking",
    title: "Elicited Difficulty Speaking",
    critical: true,
    legacyClinicalChecklistIds: ["clinical-1"],
    acceptedConcepts: ["difficulty speaking", "speech difficulty"],
  }),
  finding({
    id: "C1-CF-005",
    name: "elicited-voice-change",
    title: "Elicited Voice Change",
    critical: true,
    legacyClinicalChecklistIds: ["clinical-1"],
    acceptedConcepts: ["voice change", "muffled voice"],
  }),
  finding({
    id: "C1-CF-006",
    name: "elicited-drooling",
    title: "Elicited Drooling",
    critical: true,
    acceptedConcepts: ["drooling", "cannot handle secretions"],
  }),
  finding({
    id: "C1-CF-007",
    name: "elicited-positional-dyspnea",
    title: "Elicited Positional Dyspnea",
    critical: true,
    acceptedConcepts: ["worse lying flat", "cannot lie flat", "choking when supine"],
  }),
  neutralFinding("C1-CF-N01", "trismus-neutral", "Trismus"),
  neutralFinding("C1-CF-N02", "periorbital-swelling-neutral", "Periorbital Swelling"),
  neutralFinding(
    "C1-CF-N03",
    "inferior-border-mandible-neutral",
    "Inability to Palpate the Inferior Border of the Mandible",
  ),
  neutralFinding("C1-CF-N04", "raised-floor-mouth-neutral", "Raised Floor of Mouth"),
  neutralFinding("C1-CF-N05", "palpable-neck-swelling-neutral", "Palpable Neck Swelling"),
  neutralFinding(
    "C1-CF-N06",
    "oropharyngeal-swelling-neutral",
    "Oropharyngeal Swelling",
  ),
  interpretation({
    id: "C1-CI-001",
    name: "recognized-impending-airway-compromise",
    title: "Recognized Impending Airway Compromise",
    description: "Recognized that the airway is threatened and requires immediate protection; the prior reassuring 'patent airway' wording is not retained.",
    expectedValue: "impending airway compromise",
    critical: true,
    facultyNotes: "The prior 'airway is patent' wording was potentially reassuring despite impending compromise and should receive explicit faculty confirmation before any future reuse.",
  }),
  interpretation({
    id: "C1-CI-002",
    name: "recognized-emergency-urgency",
    title: "Recognized Emergency-Level Urgency",
    description: "Recognized the case as an emergency-level deep space infection risk.",
    expectedValue: "emergency",
    critical: true,
    legacyClinicalChecklistIds: ["clinical-5"],
  }),
  interpretation({
    id: "C1-CI-003",
    name: "diagnosed-ludwigs-angina",
    title: "Diagnosed Ludwig's Angina",
    description: "Recognized the canonical diagnosis of Ludwig's angina.",
    expectedValue: "Ludwig's angina",
    critical: true,
  }),
  interpretation({
    id: "C1-CI-004",
    name: "considered-airway-differentials",
    title: "Considered Appropriate Airway Differentials",
    description: "Considered deep neck-space abscess, epiglottitis, peritonsillar abscess, or angioedema.",
    expectedValue: ["deep neck-space abscess", "epiglottitis", "peritonsillar abscess", "angioedema"],
  }),
  recommendation({
    id: "C1-MP-001",
    name: "recommended-monitor-maintain-airway",
    title: "Recommended Monitoring and Maintaining the Airway",
    description: "Recommended monitoring and maintaining the airway.",
    critical: true,
    acceptedConcepts: ["airway monitoring", "maintain airway", "secure airway"],
  }),
  recommendation({
    id: "C1-MP-002",
    name: "recommended-omfs-consult",
    title: "Recommended OMFS or Surgical Consultation",
    description: "Recommended consultation with OMFS or a surgeon.",
    critical: true,
    acceptedConcepts: ["OMFS consult", "oral surgery consult", "surgical consultation"],
  }),
  recommendation({
    id: "C1-MP-003",
    name: "recommended-iv-antibiotics",
    title: "Recommended IV Antibiotics",
    description: "Recommended IV antibiotics for suspected deep space infection.",
    critical: true,
    acceptedConcepts: ["IV antibiotics", "intravenous antibiotics"],
  }),
  recommendation({
    id: "C1-MP-004",
    name: "selected-appropriate-iv-antibiotic",
    title: "Selected an Appropriate IV Antibiotic",
    description:
      "Selected an appropriate IV antibiotic or accepted allergy-adjusted alternative.",
    critical: true,
    acceptedConcepts: ["ampicillin-sulbactam", "clindamycin", "allergy alternative"],
    legacyClinicalChecklistIds: ["clinical-4"],
    facultyNotes: "The Word source requires IV broad-spectrum antibiotics but does not specify a single regimen; exact drug-level scoring remains a faculty decision.",
  }),
  recommendation({
    id: "C1-MP-005",
    name: "recommended-ct-with-iv-contrast",
    title: "Recommended CT With IV Contrast",
    description: "Recommended CT imaging only when safe and without delaying airway management.",
    critical: true,
    acceptedConcepts: ["CT with IV contrast", "contrast CT"],
    facultyNotes: "The Word source says CT scan without specifying contrast; exact contrast requirements remain pending faculty confirmation, and imaging must not delay airway management.",
  }),
  recommendation({
    id: "C1-MP-006",
    name: "recommended-systemic-analgesia",
    title: "Recommended Systemic Analgesia",
    description: "Recommended systemic analgesia for pain control.",
    acceptedConcepts: ["systemic analgesia", "pain control", "analgesics"],
  }),
  recommendation({
    id: "C1-MP-008",
    name: "recommended-upright-oxygen-monitoring",
    title: "Recommended Upright Positioning, Oxygen, and Monitoring",
    description: "Recommended upright positioning, oxygen, and continuous monitoring.",
    critical: true,
    acceptedConcepts: ["upright positioning", "oxygen", "continuous monitoring"],
  }),
  recommendation({
    id: "C1-MP-009",
    name: "recommended-advanced-airway-escalation",
    title: "Escalated Early for Advanced Airway Management",
    description: "Escalated early to an appropriate airway specialist for advanced airway management.",
    critical: true,
    acceptedConcepts: ["advanced airway", "anesthesia consult", "ENT consult", "airway specialist"],
  }),
  recommendation({
    id: "C1-MP-010",
    name: "recommended-admission",
    title: "Recommended Hospital Admission",
    description: "Recommended admission rather than routine discharge.",
    critical: true,
    acceptedConcepts: ["hospital admission", "admit", "do not discharge"],
  }),
  recommendation({
    id: "C1-MP-011",
    name: "recommended-source-control-after-stabilization",
    title: "Recommended Dental Source Control After Stabilization",
    description: "Recommended definitive dental source control after airway stabilization.",
    acceptedConcepts: ["source control", "extract after stabilization", "definitive dental treatment after stabilization"],
  }),
  recommendation({
    id: "C1-MP-007",
    name: "considered-npo-or-operating-room",
    title: "Considered NPO or Operating Room Management",
    description: "Considered NPO status and/or operating room management.",
    acceptedConcepts: ["NPO", "operating room", "OR management"],
  }),
  reviewedAvailableExamination({ id: "C1-EX-001" }),
  recognizedExaminationFinding({ id: "C1-EX-002", name: "recognized-bilateral-deep-space-induration", title: "Recognized Bilateral Submandibular and Sublingual Induration", acceptedConcepts: ["bilateral submandibular induration", "bilateral sublingual induration", "bilateral deep-space swelling"], critical: true }),
  recognizedExaminationFinding({ id: "C1-EX-003", name: "recognized-board-like-floor", title: "Recognized Board-like Floor of Mouth", acceptedConcepts: ["board-like floor of mouth", "tense floor of mouth"], critical: true }),
  recognizedExaminationFinding({ id: "C1-EX-004", name: "recognized-tongue-elevation", title: "Recognized Elevated or Posteriorly Displaced Tongue", acceptedConcepts: ["elevated tongue", "posterior tongue displacement"], critical: true }),
  recognizedExaminationFinding({ id: "C1-EX-005", name: "recognized-respiratory-distress", title: "Recognized Stridor or Increased Work of Breathing", acceptedConcepts: ["stridor", "increased work of breathing", "respiratory distress"], critical: true }),
  recognizedExaminationFinding({ id: "C1-EX-006", name: "recognized-fever-tachycardia", title: "Recognized Fever and Tachycardia", acceptedConcepts: ["38.6", "fever", "heart rate 112", "tachycardia"], critical: true }),
];

const case02Criteria: FacultyRubricCriterion[] = [
  shared("askedAboutFever", {
    id: "C2-IG-001",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["systemic-symptoms"],
    legacyClinicalChecklistIds: ["clinical-2"],
  }),
  criterion({
    id: "C2-IG-002",
    name: "established-penicillin-allergy-status",
    title: "Established Penicillin-Allergy Status",
    description:
      "Established whether the patient is allergic to penicillin through a relevant learner inquiry and an explicit patient response.",
    competency: "information-gathering",
    evaluationMode: "finding-elicitation",
    expectation: "required",
    source: "faculty-history-question",
    acceptedConcepts: [
      "penicillin allergy",
      "amoxicillin allergy",
      "penicillin-class allergy",
      "medication allergies",
      "drug allergies",
    ],
    reportLabel: "Established penicillin-allergy status",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["allergies"],
    legacyClinicalChecklistIds: ["clinical-4"],
  }),
  unscoredShared("askedAboutColdPain", { id: "C2-IG-003", weight: 0, critical: false, facultyNotes: "Unscored for Case 2 per confirmed Phase 1 checklist review." }),
  unscoredShared("askedAboutLingeringColdPain", { id: "C2-IG-004", weight: 0, critical: false, facultyNotes: "Unscored for Case 2 per confirmed Phase 1 checklist review; the prior lingering-answer ambiguity no longer affects scoring." }),
  unscoredShared("askedAboutBitingPain", { id: "C2-IG-005", weight: 0, critical: false, facultyNotes: "Unscored for Case 2 per confirmed Phase 1 checklist review." }),
  shared("askedAboutHomeMedicationUse", {
    id: "C2-IG-006",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["medications"],
    legacyClinicalChecklistIds: ["clinical-4"],
  }),
  finding({ id: "C2-IG-007", name: "asked-about-seven-day-progression", title: "Asked About Seven-Day Symptom Progression", acceptedConcepts: ["seven days", "one week", "progression"] }),
  finding({ id: "C2-IG-008", name: "asked-about-chills-weakness-fatigue", title: "Asked About Chills, Weakness, or Fatigue", acceptedConcepts: ["chills", "weakness", "fatigue", "feeling sick"] }),
  finding({ id: "C2-IG-009", name: "asked-about-airway-red-flags", title: "Asked About Airway and Swallowing Red Flags", acceptedConcepts: ["difficulty breathing", "swallow liquids", "voice change", "drooling", "mouth opening"], legacyPatientChecklistIds: ["airway"], legacyClinicalChecklistIds: ["clinical-2"] }),
  shared("offeredDentalAnesthesia", {
    id: "C2-PC-001",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  unscoredShared("explainedTemporaryPainRelief", { id: "C2-PC-002", weight: 0, critical: false, facultyNotes: "Unscored for Case 2 per confirmed Phase 1 checklist review." }),
  criterion({
    id: "C2-PC-003",
    name: "explained-antibiotics-do-not-resolve-source",
    title: "Explained Antibiotics Do Not Resolve the Tooth Source",
    description:
      "Explained that antibiotics already received will not resolve the underlying dental source.",
    competency: "patient-communication",
    evaluationMode: "patient-education",
    expectation: "required",
    source: "faculty-clinical-checklist",
    acceptedConcepts: ["antibiotics do not fix the tooth", "source control"],
    reportLabel: "Explained the limits of antibiotics without dental source control",
  }),
  criterion({
    id: "C2-CF-001",
    name: "airway-compromise-none-expected",
    title: "No Airway-Compromise Findings Expected",
    description:
      "Expected case state is none of the listed airway-compromise findings; no active rule-out is required.",
    competency: "clinical-findings",
    evaluationMode: "case-state",
    expectation: "expected-case-state",
    weight: 0,
    source: "faculty-clinical-checklist",
    expectedValue: "none-of-the-above",
    reportLabel: "No airway compromise expected in the case state",
  }),
  finding({
    id: "C2-CF-002",
    name: "elicited-fever",
    title: "Elicited Fever",
    legacyPatientChecklistIds: ["systemic-symptoms"],
    legacyClinicalChecklistIds: ["clinical-2"],
  }),
  finding({
    id: "C2-CF-003",
    name: "elicited-facial-swelling",
    title: "Elicited Facial Swelling",
    legacyPatientChecklistIds: ["swelling"],
    legacyClinicalChecklistIds: ["clinical-3"],
  }),
  recognizedClinicalFinding({
    id: "C2-CF-004",
    name: "recognized-tachycardia-over-100",
    title: "Recognized Tachycardia Greater Than 100 BPM",
    critical: true,
    acceptedConcepts: ["heart rate 108", "tachycardia"],
  }),
  recognizedClinicalFinding({
    id: "C2-CF-005",
    name: "recognized-systemic-infection-findings",
    title: "Recognized Systemic Infection Findings",
    critical: true,
    acceptedConcepts: ["systemic infection", "fever and tachycardia", "neutrophilic leukocytosis"],
  }),
  finding({ id: "C2-CF-006", name: "elicited-chills-and-weakness", title: "Elicited Chills, Weakness, and Fatigue", acceptedConcepts: ["chills", "weakness", "fatigue", "systemically ill"] }),
  finding({ id: "C2-CF-007", name: "elicited-negative-airway-screen", title: "Elicited Negative Airway and Swallowing Screen", acceptedConcepts: ["no dyspnea", "can swallow liquids", "normal voice", "no drooling"] }),
  interpretation({
    id: "C2-CI-001",
    name: "recognized-emergency-urgency",
    title: "Recognized Emergency-Level Urgency",
    description: "Recognized the case as emergency-level urgency.",
    expectedValue: "emergency",
    critical: true,
    legacyClinicalChecklistIds: ["clinical-5"],
  }),
  interpretation({ id: "C2-CI-002", name: "diagnosed-systemic-odontogenic-infection", title: "Diagnosed Odontogenic Abscess with Cellulitis and Systemic Infection", description: "Recognized the complete canonical diagnosis rather than a localized-only abscess.", expectedValue: "odontogenic abscess with cellulitis and systemic infection", critical: true }),
  interpretation({ id: "C2-CI-003", name: "recognized-no-deep-space-involvement", title: "Recognized No Deep-Space Involvement on CT", description: "Correctly interpreted the CT as showing cellulitis without deep-space involvement.", expectedValue: "no deep-space involvement", critical: true }),
  interpretation({ id: "C2-CI-004", name: "recognized-progression-risk", title: "Recognized Risk of Infection Progression", description: "Recognized progression risk despite the current absence of deep-space involvement.", expectedValue: "risk of progression" }),
  recommendation({
    id: "C2-MP-001",
    name: "recommended-omfs-admission-consult",
    title: "Recommended OMFS or Surgical Admission Consultation",
    description: "Recommended OMFS or surgeon consultation for admission.",
    critical: true,
  }),
  recommendation({ id: "C2-MP-007", name: "recommended-lactate", title: "Recommended Lactate Testing", description: "Recommended lactate testing in the systemic-infection evaluation.", acceptedConcepts: ["lactate"] }),
  recommendation({ id: "C2-MP-008", name: "recommended-fluids-antipyretics", title: "Recommended IV Fluids and Antipyretic Treatment", description: "Recommended IV fluids and treatment of fever.", acceptedConcepts: ["IV fluids", "antipyretic", "treat fever"] }),
  recommendation({ id: "C2-MP-009", name: "recommended-possible-admission", title: "Considered Hospital Admission", description: "Considered hospital admission in the emergency systemic-infection context.", critical: true, acceptedConcepts: ["admission", "admit", "hospitalize"] }),
  recommendation({ id: "C2-MP-010", name: "recommended-source-control-72-hours", title: "Recommended Definitive Dental Source Control Within 72 Hours", description: "Recommended definitive dental treatment or source control within approximately 72 hours.", critical: true, acceptedConcepts: ["source control", "dental treatment within 72 hours", "definitive dental care"] }),
  recommendation({
    id: "C2-MP-002",
    name: "recommended-cbc-bmp",
    title: "Recommended CBC and BMP",
    description: "Recommended CBC and BMP laboratory evaluation.",
    acceptedConcepts: ["CBC", "BMP", "basic metabolic panel"],
  }),
  recommendation({
    id: "C2-MP-003",
    name: "recommended-iv-antibiotics",
    title: "Recommended IV Antibiotics",
    description:
      "Recommended IV antibiotics because systemic infection and swelling make oral-only treatment insufficient.",
    critical: true,
    legacyClinicalChecklistIds: ["clinical-4"],
  }),
  recommendation({
    id: "C2-MP-004",
    name: "selected-appropriate-iv-antibiotic",
    title: "Selected an Appropriate IV Antibiotic",
    description:
      "Selected an appropriate IV antibiotic or accepted allergy-adjusted alternative.",
    critical: true,
    acceptedConcepts: ["ampicillin-sulbactam", "clindamycin", "allergy alternative"],
    legacyClinicalChecklistIds: ["clinical-4"],
  }),
  recommendation({
    id: "C2-MP-005",
    name: "recommended-ct-with-iv-contrast",
    title: "Recommended CT With IV Contrast",
    description: "Recommended CT with IV contrast.",
    critical: true,
  }),
  recommendation({
    id: "C2-MP-006",
    name: "recommended-systemic-analgesia",
    title: "Recommended Systemic Analgesia",
    description: "Recommended systemic analgesia.",
  }),
  reviewedAvailableExamination({ id: "C2-EX-001" }),
  recognizedExaminationFinding({ id: "C2-EX-002", name: "recognized-fever-tachycardia", title: "Recognized Fever and Tachycardia", acceptedConcepts: ["38.4", "heart rate 108", "fever", "tachycardia"], critical: true }),
  recognizedExaminationFinding({ id: "C2-EX-003", name: "recognized-oral-facial-findings", title: "Recognized Upper-Right Gingival and Cheek Findings", acceptedConcepts: ["upper-right gingival erythema", "gingival swelling", "cheek swelling", "gingival tenderness"] }),
  recognizedExaminationFinding({ id: "C2-EX-004", name: "recognized-tooth-tenderness", title: "Recognized Marked Touch and Percussion Tenderness", acceptedConcepts: ["tender to touch", "percussion tenderness"] }),
  recognizedExaminationFinding({ id: "C2-EX-005", name: "recognized-wbc-neutrophilia", title: "Recognized WBC 14.8 with Neutrophilia", acceptedConcepts: ["WBC 14.8", "neutrophilic leukocytosis", "neutrophil predominant"] }),
  recognizedExaminationFinding({ id: "C2-EX-006", name: "recognized-normal-lactate-bmp", title: "Recognized Normal Lactate and BMP", acceptedConcepts: ["normal lactate", "normal BMP", "normal basic metabolic panel"] }),
  recognizedExaminationFinding({ id: "C2-EX-007", name: "recognized-ct-abscess-cellulitis", title: "Recognized CT Abscess and Facial Cellulitis", acceptedConcepts: ["periapical abscess", "facial cellulitis", "surrounding cellulitis"], critical: true }),
  recognizedExaminationFinding({ id: "C2-EX-008", name: "recognized-ct-no-deep-space", title: "Recognized No Deep-Space Involvement", acceptedConcepts: ["no deep-space involvement", "no deep space involvement"], critical: true }),
];

const case03Criteria: FacultyRubricCriterion[] = [
  shared("askedAboutFever", {
    id: "C3-IG-001",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["fever"],
    legacyClinicalChecklistIds: ["clinical-3"],
  }),
  shared("askedAboutPenicillinAllergy", {
    id: "C3-IG-002",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["allergies"],
  }),
  finding({
    id: "C3-IG-010",
    name: "asked-about-general-medication-allergies",
    title: "Asked About General Medication Allergies",
    acceptedConcepts: ["medication allergies", "drug allergies", "allergies to medicines"],
    legacyPatientChecklistIds: ["allergies"],
  }),
  shared("askedAboutColdPain", {
    id: "C3-IG-003",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  shared("askedAboutLingeringColdPain", {
    id: "C3-IG-004",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  shared("askedAboutBitingPain", {
    id: "C3-IG-005",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["biting-pain"],
  }),
  shared("askedAboutHomeMedicationUse", {
    id: "C3-IG-006",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["medications"],
  }),
  finding({ id: "C3-IG-007", name: "elicited-ulcer-and-nsaid-history", title: "Elicited Ulcer History and NSAID Intolerance", acceptedConcepts: ["stomach ulcers", "ibuprofen upsets stomach", "NSAID intolerance"], legacyClinicalChecklistIds: ["clinical-2"] }),
  finding({ id: "C3-IG-008", name: "elicited-radiation", title: "Elicited Radiation Toward the Right Ear", acceptedConcepts: ["right ear", "radiates to the right ear"] }),
  finding({ id: "C3-IG-009", name: "elicited-airway-and-trismus-negatives", title: "Elicited Airway, Swallowing, Voice, and Trismus Negatives", acceptedConcepts: ["no difficulty breathing", "no difficulty swallowing", "no voice change", "no trismus"], legacyClinicalChecklistIds: ["clinical-3"] }),
  shared("offeredDentalAnesthesia", {
    id: "C3-PC-001",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  shared("explainedTemporaryPainRelief", {
    id: "C3-PC-002",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  recommendation({
    id: "C3-MP-001",
    name: "offered-incision-and-drainage",
    title: "Offered Incision and Drainage",
    description: "Offered incision and drainage of the abscess to relieve pain.",
    acceptedConcepts: ["incision and drainage", "drain the abscess", "I and D"],
  }),
  recommendation({
    id: "C3-MP-002",
    name: "preferred-acetaminophen-with-dose-review",
    title: "Recommended Acetaminophen or Tylenol",
    description: "Recommended acetaminophen or Tylenol for pain because ibuprofen is not tolerated, without requiring an unapproved dose.",
    acceptedConcepts: ["acetaminophen", "Tylenol"],
    facultyNotes: "Exact acetaminophen dose, interval, and maximum daily amount remain pending faculty review; do not score a specific schedule.",
  }),
  recommendation({
    id: "C3-MP-007",
    name: "recommended-nsaid-despite-ulcer-intolerance",
    title: "Recommended NSAID Despite Ulcer History and Intolerance",
    description:
      "Affirmatively recommended ibuprofen, Advil, Motrin, or another NSAID despite the patient's stomach-ulcer history and documented intolerance.",
    critical: true,
    acceptedConcepts: [
      "ibuprofen",
      "Advil",
      "Motrin",
      "NSAID",
      "naproxen",
      "Aleve",
      "ketorolac",
      "Toradol",
      "diclofenac",
      "celecoxib",
      "Celebrex",
    ],
    expectedValue: false,
    facultyNotes:
      "Faculty clarification requires Tylenol only; negation, avoidance counseling, and historical discussion of NSAID intolerance do not count as this unsafe recommendation.",
  }),
  shared("recommendedPromptDentalFollowUp", {
    id: "C3-MP-003",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  recommendation({ id: "C3-MP-004", name: "recommended-antibiotic", title: "Recommended Canonical Antibiotic Therapy", description: "Recommended antibiotic therapy for the canonical abscess scenario without inventing an escalation regimen.", acceptedConcepts: ["antibiotic", "antibiotic therapy"] }),
  recommendation({ id: "C3-MP-005", name: "explained-temporary-ed-care", title: "Explained ED Treatment Is Temporary", description: "Explained that drainage or antibiotics do not replace definitive dental treatment.", acceptedConcepts: ["temporary", "does not replace dental treatment", "still need a dentist", "definitive dental care"] }),
  recommendation({ id: "C3-MP-006", name: "provided-safety-net", title: "Provided Abscess Safety-Net Instructions", description: "Advised return for worsening swelling, fever, swallowing or breathing difficulty, or voice change.", acceptedConcepts: ["worsening swelling", "fever", "difficulty swallowing", "difficulty breathing", "voice change"] }),
  criterion({
    id: "C3-CF-001",
    name: "airway-compromise-none-expected",
    title: "No Airway-Compromise Findings Expected",
    description:
      "Expected case state is none of the listed airway-compromise findings; no active rule-out is required.",
    competency: "clinical-findings",
    evaluationMode: "case-state",
    expectation: "expected-case-state",
    weight: 0,
    source: "faculty-clinical-checklist",
    expectedValue: "none-of-the-above",
    reportLabel: "No airway compromise expected in the case state",
  }),
  finding({
    id: "C3-CF-002",
    name: "elicited-intraoral-abscess",
    title: "Elicited Intraoral Abscess",
    legacyClinicalChecklistIds: ["clinical-5"],
    acceptedConcepts: ["intraoral abscess", "localized abscess"],
  }),
  criterion({
    id: "C3-CF-003",
    name: "clinical-instability-none-expected",
    title: "No Clinical Instability Expected",
    description:
      "Expected case state is none of the listed clinical instability findings; no active rule-out is required.",
    competency: "clinical-findings",
    evaluationMode: "case-state",
    expectation: "expected-case-state",
    weight: 0,
    source: "faculty-clinical-checklist",
    expectedValue: "none-of-the-above",
    reportLabel: "No clinical instability expected in the case state",
  }),
  interpretation({
    id: "C3-CI-001",
    name: "recognized-urgent-case",
    title: "Recognized Urgent Case",
    description: "Recognized the case as urgent rather than routine.",
    expectedValue: "urgent",
  }),
  interpretation({ id: "C3-CI-004", name: "diagnosed-right-mandibular-periapical-abscess", title: "Diagnosed Right Mandibular Periapical Abscess", description: "Identified the primary diagnosis and canonical mandibular location without periodontal framing.", expectedValue: "right mandibular periapical abscess", legacyClinicalChecklistIds: ["clinical-5"] }),
  interpretation({
    id: "C3-CI-002",
    name: "recognized-local-intraoral-abscess",
    title: "Recognized Local Intraoral Abscess",
    description: "Recognized that a local intraoral abscess is present.",
    expectedValue: true,
    legacyClinicalChecklistIds: ["clinical-5"],
  }),
  interpretation({
    id: "C3-CI-003",
    name: "recognized-ct-not-recommended",
    title: "Recognized CT Is Not Recommended",
    description: "Recognized that CT is not recommended when a local intraoral abscess is present.",
    expectedValue: true,
  }),
  criterion({
    id: "C3-PD-001",
    name: "selected-mandibular-anesthesia",
    title: "Selected Appropriate Mandibular Anesthesia",
    description: "Selected a clinically appropriate dental block or local anesthesia approach for a right mandibular posterior tooth.",
    competency: "procedural-decision",
    evaluationMode: "procedural-choice",
    expectation: "required",
    expectedValue: true,
    source: "faculty-clinical-checklist",
    acceptedConcepts: ["inferior alveolar nerve block", "mandibular block", "dental block", "local anesthesia"],
    reportLabel: "Selected an appropriate mandibular anesthesia approach",
  }),
  criterion({
    id: "C3-PD-002",
    name: "localized-procedure-to-right-mandible",
    title: "Localized the Procedure to the Right Mandibular Tooth",
    description: "Localized anesthesia and drainage to the right mandibular posterior tooth rather than a maxillary site.",
    competency: "procedural-decision",
    evaluationMode: "procedural-choice",
    expectation: "required",
    expectedValue: true,
    source: "faculty-clinical-checklist",
    acceptedConcepts: ["right mandibular", "lower right", "mandibular posterior tooth"],
    reportLabel: "Localized the procedure to the right mandibular tooth",
  }),
  criterion({
    id: "C3-PD-003",
    name: "selected-recommended-local-anesthetic-concept",
    title: "Selected Recommended Local Anesthetic Concept",
    description:
      "Accepted a clinically appropriate mandibular local-anesthetic strategy without requiring one exact technique or formulation.",
    competency: "procedural-decision",
    evaluationMode: "procedural-choice",
    expectation: "required",
    source: "faculty-clinical-checklist",
    acceptedConcepts: [
      "inferior alveolar nerve block",
      "mandibular block",
      "local anesthesia",
      "2% lidocaine with 1:100,000 epinephrine",
      "0.5% bupivacaine with 1:200,000 epinephrine",
    ],
    reportLabel: "Chose an appropriate local anesthetic strategy",
    facultyNotes:
      "Exact formulation remains a supporting concept pending faculty calibration; the canonical source does not require one exclusive mandibular technique.",
  }),
  reviewedAvailableExamination({ id: "C3-EX-001" }),
  recognizedExaminationFinding({ id: "C3-EX-002", name: "recognized-right-mandibular-localization", title: "Recognized Right Mandibular Localization", acceptedConcepts: ["right mandibular", "lower-right posterior tooth", "right mandibular first molar"] }),
  recognizedExaminationFinding({ id: "C3-EX-003", name: "recognized-fluctuance-purulence", title: "Recognized Fluctuance and Purulence", acceptedConcepts: ["fluctuance", "purulence", "purulent drainage"], critical: true }),
  recognizedExaminationFinding({ id: "C3-EX-004", name: "recognized-percussion-biting-palpation", title: "Recognized Percussion, Biting, and Palpation Tenderness", acceptedConcepts: ["percussion tenderness", "biting tenderness", "palpation tenderness"] }),
  recognizedExaminationFinding({ id: "C3-EX-005", name: "recognized-cold-negative", title: "Recognized Negative Cold Response", acceptedConcepts: ["no cold response", "cold-negative", "negative cold test"] }),
  recognizedExaminationFinding({ id: "C3-EX-006", name: "recognized-safe-floor-airway", title: "Recognized Soft Floor and Patent Airway", acceptedConcepts: ["soft floor of mouth", "floor of mouth not elevated", "no stridor", "patent airway", "no voice change"] }),
];

const case04Criteria: FacultyRubricCriterion[] = [
  shared("askedAboutFever", {
    id: "C4-IG-001",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["systemic-symptoms"],
    legacyClinicalChecklistIds: ["clinical-2"],
  }),
  shared("askedAboutPenicillinAllergy", {
    id: "C4-IG-002",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["allergies"],
  }),
  finding({
    id: "C4-IG-012",
    name: "asked-about-general-medication-allergies",
    title: "Asked About General Medication Allergies",
    acceptedConcepts: ["medication allergies", "drug allergies", "allergies to medicines"],
    legacyPatientChecklistIds: ["allergies"],
  }),
  shared("askedAboutColdPain", {
    id: "C4-IG-003",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["thermal-sensitivity"],
    legacyClinicalChecklistIds: ["clinical-4"],
    facultyNotes: "Assess historical patient-reported cold pain separately from the current examination response.",
  }),
  shared("askedAboutLingeringColdPain", {
    id: "C4-IG-004",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["thermal-sensitivity"],
    legacyClinicalChecklistIds: ["clinical-4"],
    facultyNotes: "Use this follow-up to assess current loss of cold response; do not imply current lingering sensitivity.",
  }),
  shared("askedAboutBitingPain", {
    id: "C4-IG-005",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["biting-pain"],
    legacyClinicalChecklistIds: ["clinical-1"],
  }),
  shared("askedAboutHomeMedicationUse", {
    id: "C4-IG-006",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["medications"],
  }),
  finding({ id: "C4-IG-007", name: "elicited-five-day-sequence", title: "Elicited Five-Day Course and Stop-Return Sequence", acceptedConcepts: ["five days", "stopped then returned", "pain returned", "last 48 hours"], legacyClinicalChecklistIds: ["clinical-1"] }),
  finding({ id: "C4-IG-008", name: "elicited-constant-seven-of-ten-pain", title: "Elicited Constant 7/10 Pain", acceptedConcepts: ["constant pain", "7/10", "seven out of ten"], legacyClinicalChecklistIds: ["clinical-1"] }),
  finding({ id: "C4-IG-009", name: "elicited-penicillin-hives", title: "Elicited Penicillin Hives Reaction", acceptedConcepts: ["penicillin causes hives", "hives from penicillin"], legacyPatientChecklistIds: ["allergy-reaction"], legacyClinicalChecklistIds: ["clinical-3"] }),
  finding({ id: "C4-IG-010", name: "elicited-negative-infection-screen", title: "Elicited Negative Infection and Airway Screen", acceptedConcepts: ["no swelling", "no drainage", "no fever", "no difficulty swallowing", "no difficulty breathing"], legacyClinicalChecklistIds: ["clinical-2"] }),
  finding({ id: "C4-IG-011", name: "elicited-access-and-tooth-goal", title: "Elicited Dental Access Barrier and Tooth-Saving Goal", acceptedConcepts: ["no dental insurance", "access will take time", "wants to save the tooth"], legacyPatientChecklistIds: ["dental-access", "patient-goals"] }),
  shared("offeredDentalAnesthesia", {
    id: "C4-PC-001",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  shared("explainedTemporaryPainRelief", {
    id: "C4-PC-002",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  shared("explainedAntibioticsNotIndicated", {
    id: "C4-PC-003",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  criterion({
    id: "C4-PC-004",
    name: "explained-when-antibiotics-indicated",
    title: "Explained When Antibiotics Would Become Indicated",
    description:
      "Explained that antibiotics become indicated with swelling, systemic illness, spreading infection, or related infection signs.",
    competency: "patient-communication",
    evaluationMode: "patient-education",
    expectation: "required",
    source: "faculty-clinical-checklist",
    acceptedConcepts: ["fever", "swelling", "spreading infection", "systemic illness"],
    reportLabel: "Explained when antibiotics would become indicated",
    facultyNotes: "Delayed-prescription language remains pending faculty review and is not required or scored; assess reassessment and return precautions only.",
  }),
  shared("recommendedPromptDentalFollowUp", {
    id: "C4-MP-001",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  recommendation({ id: "C4-MP-002", name: "recommended-appropriate-analgesia", title: "Recommended Appropriate Analgesia", description: "Recommended an appropriate analgesic plan for severe dental pain.", acceptedConcepts: ["ibuprofen", "acetaminophen", "analgesia", "pain control"] }),
  recommendation({ id: "C4-MP-003", name: "recommended-definitive-pulpal-treatment", title: "Recommended Root Canal or Extraction", description: "Recommended urgent definitive dental treatment with root-canal treatment or extraction based on dental evaluation.", acceptedConcepts: ["root canal", "endodontic treatment", "extraction", "definitive dental treatment"], critical: true }),
  recommendation({ id: "C4-MP-004", name: "planned-around-access-barrier", title: "Addressed Dental Access Barrier", description: "Developed a practical urgent follow-up plan for a patient without dental insurance.", acceptedConcepts: ["dental access", "no insurance", "low-cost clinic", "urgent dental clinic", "financial assistance"] }),
  shared("askedAboutDentalFollowUpAccess", {
    id: "C4-PC-005",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  shared("askedWhetherPatientWantsToSaveTooth", {
    id: "C4-PC-006",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["patient-goals"],
  }),
  criterion({
    id: "C4-CF-001",
    name: "airway-compromise-none-expected",
    title: "No Airway-Compromise Findings Expected",
    description:
      "Expected case state is none of the listed airway-compromise findings; no active rule-out is required.",
    competency: "clinical-findings",
    evaluationMode: "case-state",
    expectation: "expected-case-state",
    weight: 0,
    source: "faculty-clinical-checklist",
    expectedValue: "none-of-the-above",
    reportLabel: "No airway compromise expected in the case state",
  }),
  criterion({
    id: "C4-CF-002",
    name: "systemic-infection-none-expected",
    title: "No Systemic Infection or Abscess Findings Expected",
    description:
      "Expected case state is none of the listed systemic infection or abscess findings; no active rule-out is required.",
    competency: "clinical-findings",
    evaluationMode: "case-state",
    expectation: "expected-case-state",
    weight: 0,
    source: "faculty-clinical-checklist",
    expectedValue: "none-of-the-above",
    reportLabel: "No systemic infection or abscess expected in the case state",
  }),
  finding({
    id: "C4-CF-003",
    name: "elicited-constant-current-pain",
    title: "Elicited Constant Current Pain",
    legacyClinicalChecklistIds: ["clinical-4"],
    acceptedConcepts: ["constant pain", "pain all the time", "unprovoked pain"],
  }),
  interpretation({
    id: "C4-CI-001",
    name: "recognized-urgent-case",
    title: "Recognized Urgent Case",
    description: "Recognized the case as urgent.",
    expectedValue: "urgent",
  }),
  interpretation({ id: "C4-CI-005", name: "recognized-acute-apical-periodontitis", title: "Recognized Acute Apical Periodontitis", description: "Connected marked percussion and biting tenderness with acute apical periodontitis.", expectedValue: "acute apical periodontitis", legacyClinicalChecklistIds: ["clinical-5"] }),
  interpretation({ id: "C4-CI-006", name: "recognized-no-current-abscess-or-systemic-infection", title: "Recognized No Current Abscess or Systemic Infection", description: "Recognized that swelling, fluctuance, purulence, fever, and systemic infection are absent and routine antibiotics are not indicated.", expectedValue: false, legacyClinicalChecklistIds: ["clinical-2"] }),
  interpretation({
    id: "C4-CI-002",
    name: "recognized-necrotic-pulp",
    title: "Recognized Necrotic Pulp",
    description: "Recognized necrotic pulp as the expected interpretation.",
    expectedValue: "necrotic pulp",
    legacyClinicalChecklistIds: ["clinical-5"],
  }),
  interpretation({
    id: "C4-CI-003",
    name: "recognized-loss-of-vitality-pattern",
    title: "Recognized the Loss-of-Vitality Pattern",
    description: "Connected prior severe cold pain that stopped with the current absent cold response and ongoing percussion pain.",
    expectedValue: true,
    legacyClinicalChecklistIds: ["clinical-4"],
  }),
  interpretation({
    id: "C4-CI-004",
    name: "recognized-percussion-pain",
    title: "Recognized Pain With Tapping or Percussion",
    description: "Recognized pain with tapping or percussion.",
    expectedValue: true,
    legacyClinicalChecklistIds: ["clinical-1"],
  }),
  criterion({
    id: "C4-PD-001",
    name: "offered-appropriate-mandibular-local-anesthesia",
    title: "Offered Appropriate Mandibular Local Anesthesia",
    description: "Offered a clinically appropriate dental block or local anesthesia for a left mandibular first molar; the patient may decline.",
    competency: "procedural-decision",
    evaluationMode: "procedural-choice",
    expectation: "required",
    source: "faculty-clinical-checklist",
    expectedValue: true,
    acceptedConcepts: ["inferior alveolar nerve block", "mandibular block", "dental block", "local anesthesia"],
    reportLabel: "Selected the tooth-location appropriate anesthetic approach",
    facultyNotes: "Credit the offer even if the standardized patient declines the block.",
  }),
  reviewedAvailableExamination({ id: "C4-EX-001" }),
  recognizedExaminationFinding({ id: "C4-EX-002", name: "recognized-left-mandibular-location", title: "Recognized Left Mandibular First-Molar Location", acceptedConcepts: ["left mandibular first molar", "lower-left first molar", "left mandibular posterior tooth"] }),
  recognizedExaminationFinding({ id: "C4-EX-003", name: "recognized-no-cold-response", title: "Recognized Absent Current Cold Response", acceptedConcepts: ["no response to cold", "absent cold response", "cold-negative"], critical: true }),
  recognizedExaminationFinding({ id: "C4-EX-004", name: "recognized-percussion-biting-tenderness", title: "Recognized Marked Percussion and Biting Tenderness", acceptedConcepts: ["percussion tenderness", "biting tenderness", "tender to percussion"] }),
  recognizedExaminationFinding({ id: "C4-EX-005", name: "recognized-large-filling-deep-caries", title: "Recognized Large Filling or Deep Caries", acceptedConcepts: ["large old filling", "deep caries", "deep carious lesion"] }),
  recognizedExaminationFinding({ id: "C4-EX-006", name: "recognized-no-abscess-findings", title: "Recognized No Abscess Findings", acceptedConcepts: ["no swelling", "no fluctuance", "no purulence", "no pus", "no sinus tract"] }),
  recognizedExaminationFinding({ id: "C4-EX-007", name: "recognized-soft-floor-patent-airway", title: "Recognized Soft Floor and Patent Airway", acceptedConcepts: ["soft floor of mouth", "patent airway", "normal voice", "no drooling"] }),
];

const case05Criteria: FacultyRubricCriterion[] = [
  shared("askedAboutFever", {
    id: "C5-IG-001",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["systemic-symptoms"],
    legacyClinicalChecklistIds: ["clinical-3"],
  }),
  shared("askedAboutPenicillinAllergy", {
    id: "C5-IG-002",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["allergies"],
    legacyClinicalChecklistIds: ["clinical-4"],
  }),
  finding({
    id: "C5-IG-012",
    name: "asked-about-general-medication-allergies",
    title: "Asked About General Medication Allergies",
    acceptedConcepts: ["medication allergies", "drug allergies", "allergies to medicines"],
    legacyPatientChecklistIds: ["allergies"],
  }),
  shared("askedAboutColdPain", {
    id: "C5-IG-003",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["thermal-sensitivity"],
    legacyClinicalChecklistIds: ["clinical-2"],
  }),
  shared("askedAboutLingeringColdPain", {
    id: "C5-IG-004",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["thermal-sensitivity"],
    legacyClinicalChecklistIds: ["clinical-2"],
  }),
  shared("askedAboutBitingPain", {
    id: "C5-IG-005",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["biting-pain"],
    legacyClinicalChecklistIds: ["clinical-1"],
  }),
  shared("askedAboutHomeMedicationUse", {
    id: "C5-IG-006",
    weight: 1,
    critical: false,
    legacyPatientChecklistIds: ["medications"],
    legacyClinicalChecklistIds: ["clinical-4"],
  }),
  finding({ id: "C5-IG-007", name: "elicited-four-day-lower-left-course", title: "Elicited Four-Day Lower-Left Course", acceptedConcepts: ["four days", "lower-left", "lower left"], legacyClinicalChecklistIds: ["clinical-1"] }),
  finding({ id: "C5-IG-008", name: "elicited-constant-deep-throbbing-nine-of-ten", title: "Elicited Constant Deep Throbbing 9/10 Pain", acceptedConcepts: ["constant", "deep", "throbbing", "9/10", "nine out of ten"], legacyPatientChecklistIds: ["pain-character"], legacyClinicalChecklistIds: ["clinical-1"] }),
  finding({ id: "C5-IG-009", name: "elicited-spontaneous-nocturnal-pain", title: "Elicited Spontaneous Nocturnal Pain and Sleep Disruption", acceptedConcepts: ["spontaneous pain", "wakes at night", "sleep disruption", "cannot sleep"], legacyPatientChecklistIds: ["spontaneous-pain", "nocturnal-pain"], legacyClinicalChecklistIds: ["clinical-1"] }),
  finding({ id: "C5-IG-010", name: "elicited-negative-infection-airway-screen", title: "Elicited Negative Infection and Airway Screen", acceptedConcepts: ["no fever", "no swelling", "no drainage", "no difficulty swallowing", "no difficulty breathing"], legacyPatientChecklistIds: ["swelling", "drainage", "systemic-symptoms", "airway"], legacyClinicalChecklistIds: ["clinical-3"] }),
  finding({ id: "C5-IG-011", name: "elicited-access-smoking-and-goal", title: "Elicited Smoking, Access Barrier, and Tooth-Saving Goal", acceptedConcepts: ["half a pack", "no insurance", "cannot afford", "wants to save the tooth"], legacyPatientChecklistIds: ["social-history", "dental-access", "patient-goals"], legacyClinicalChecklistIds: ["clinical-4"] }),
  shared("offeredDentalAnesthesia", {
    id: "C5-PC-001",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  shared("explainedTemporaryPainRelief", {
    id: "C5-PC-002",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  shared("explainedAntibioticsNotIndicated", {
    id: "C5-PC-003",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  shared("recommendedPromptDentalFollowUp", {
    id: "C5-MP-001",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  recommendation({ id: "C5-MP-002", name: "recommended-appropriate-analgesia", title: "Recommended Appropriate Analgesia", description: "Recommended an appropriate analgesic plan for severe pulpal pain.", acceptedConcepts: ["ibuprofen", "acetaminophen", "analgesia", "pain control"] }),
  recommendation({ id: "C5-MP-003", name: "recommended-root-canal-or-extraction", title: "Recommended Root Canal or Extraction", description: "Recommended urgent definitive dental treatment with root-canal treatment or extraction based on dental evaluation.", acceptedConcepts: ["root canal", "endodontic treatment", "extraction", "definitive dental treatment"], critical: true }),
  recommendation({ id: "C5-MP-004", name: "planned-around-financial-access-barrier", title: "Addressed Financial and Insurance Barriers", description: "Developed a practical urgent dental plan around unemployment, lack of insurance, and affordability barriers.", acceptedConcepts: ["no insurance", "unemployed", "cannot afford", "low-cost clinic", "financial assistance", "dental access"] }),
  recommendation({ id: "C5-MP-005", name: "provided-infection-safety-net", title: "Provided Infection and Airway Safety Net", description: "Advised reassessment for swelling, fever, drainage, swallowing or breathing difficulty, voice change, or drooling.", acceptedConcepts: ["swelling", "fever", "drainage", "difficulty swallowing", "difficulty breathing", "voice change", "drooling"] }),
  shared("askedAboutDentalFollowUpAccess", {
    id: "C5-PC-004",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  shared("askedWhetherPatientWantsToSaveTooth", {
    id: "C5-PC-005",
    weight: 1,
    critical: false,
    provisionalWeight: true,
  }),
  criterion({
    id: "C5-CF-001",
    name: "airway-compromise-none-expected",
    title: "No Airway-Compromise Findings Expected",
    description:
      "Expected case state is none of the listed airway-compromise findings; no active rule-out is required.",
    competency: "clinical-findings",
    evaluationMode: "case-state",
    expectation: "expected-case-state",
    weight: 0,
    source: "faculty-clinical-checklist",
    expectedValue: "none-of-the-above",
    reportLabel: "No airway compromise expected in the case state",
  }),
  criterion({
    id: "C5-CF-002",
    name: "systemic-infection-none-expected",
    title: "No Systemic Infection or Abscess Findings Expected",
    description:
      "Expected case state is none of the listed systemic infection or abscess findings; no active rule-out is required.",
    competency: "clinical-findings",
    evaluationMode: "case-state",
    expectation: "expected-case-state",
    weight: 0,
    source: "faculty-clinical-checklist",
    expectedValue: "none-of-the-above",
    reportLabel: "No systemic infection or abscess expected in the case state",
  }),
  finding({
    id: "C5-CF-003",
    name: "elicited-throbbing-pain",
    title: "Elicited Throbbing Pain",
    legacyPatientChecklistIds: ["pain-character"],
    legacyClinicalChecklistIds: ["clinical-1"],
    acceptedConcepts: ["throbbing pain"],
  }),
  finding({ id: "C5-CF-005", name: "elicited-nocturnal-sleep-disruption", title: "Elicited Nocturnal Pain and Sleep Disruption", acceptedConcepts: ["wakes at night", "cannot sleep", "sleep disruption", "nocturnal pain"], legacyClinicalChecklistIds: ["clinical-1"] }),
  finding({
    id: "C5-CF-004",
    name: "elicited-spontaneous-unprovoked-pain",
    title: "Elicited Spontaneous Unprovoked Pain",
    legacyPatientChecklistIds: ["pain-character"],
    legacyClinicalChecklistIds: ["clinical-1"],
    acceptedConcepts: ["spontaneous pain", "unprovoked pain", "night pain"],
  }),
  interpretation({
    id: "C5-CI-001",
    name: "recognized-urgent-case",
    title: "Recognized Urgent Case",
    description: "Recognized the case as urgent.",
    expectedValue: "urgent",
  }),
  interpretation({ id: "C5-CI-006", name: "recognized-no-current-abscess-or-systemic-infection", title: "Recognized No Current Abscess or Systemic Infection", description: "Recognized the absence of swelling, purulence, fever, and systemic illness and therefore no current antibiotic indication.", expectedValue: false, legacyClinicalChecklistIds: ["clinical-3"] }),
  interpretation({
    id: "C5-CI-002",
    name: "recognized-irreversible-pulpitis",
    title: "Recognized Irreversible Pulpitis",
    description: "Recognized irreversible pulpitis as the expected interpretation.",
    expectedValue: "irreversible pulpitis",
    legacyClinicalChecklistIds: ["clinical-5"],
  }),
  interpretation({
    id: "C5-CI-003",
    name: "recognized-lingering-cold-pain",
    title: "Recognized Cold Pain Is Exaggerated or Lingering",
    description: "Recognized exaggerated or lingering cold pain.",
    expectedValue: true,
    legacyClinicalChecklistIds: ["clinical-2"],
  }),
  interpretation({
    id: "C5-CI-004",
    name: "recognized-ct-not-recommended",
    title: "Recognized CT Is Not Recommended",
    description: "Recognized that CT is not recommended.",
    expectedValue: true,
  }),
  interpretation({
    id: "C5-CI-005",
    name: "recognized-antibiotics-not-recommended",
    title: "Recognized Antibiotics Are Not Recommended",
    description: "Recognized that antibiotics are not recommended.",
    expectedValue: true,
  }),
  criterion({
    id: "C5-PD-001",
    name: "selected-inferior-alveolar-block",
    title: "Selected Inferior Alveolar Nerve Block",
    description: "Selected inferior alveolar nerve block for mandibular teeth.",
    competency: "procedural-decision",
    evaluationMode: "procedural-choice",
    expectation: "required",
    source: "faculty-clinical-checklist",
    expectedValue: true,
    reportLabel: "Selected the mandibular block approach",
  }),
  criterion({
    id: "C5-PD-002",
    name: "selected-recommended-local-anesthetic-concept",
    title: "Selected Recommended Local Anesthetic Concept",
    description:
      "Represented the faculty-source anesthetic formulation as an accepted supporting concept pending scoring calibration.",
    competency: "procedural-decision",
    evaluationMode: "procedural-choice",
    expectation: "required",
    source: "faculty-clinical-checklist",
    acceptedConcepts: [
      "2% lidocaine with 1:100,000 epinephrine",
      "0.5% bupivacaine with 1:200,000 epinephrine",
    ],
    reportLabel: "Chose an appropriate local anesthetic strategy",
    facultyNotes:
      "Faculty should confirm whether exact formulation is a scored criterion or supporting concept.",
  }),
  reviewedAvailableExamination({ id: "C5-EX-001" }),
  recognizedExaminationFinding({ id: "C5-EX-002", name: "recognized-left-mandibular-cavity", title: "Recognized Large Left Mandibular First-Molar Cavity", acceptedConcepts: ["large cavity", "left mandibular first molar", "lower-left first molar"] }),
  recognizedExaminationFinding({ id: "C5-EX-003", name: "recognized-cold-provocation", title: "Recognized Cold-Provoked Pain", acceptedConcepts: ["cold worsens pain", "cold-provoked pain", "pain with cold"] }),
  recognizedExaminationFinding({ id: "C5-EX-004", name: "recognized-lingering-cold-response", title: "Recognized Lingering Pain After Cold Removal", acceptedConcepts: ["lingers after cold", "does not stop immediately", "persists after cold removal"], critical: true }),
  recognizedExaminationFinding({ id: "C5-EX-005", name: "recognized-slight-biting-percussion", title: "Recognized Slight Biting and Percussion Tenderness", acceptedConcepts: ["slight biting tenderness", "slight percussion tenderness", "slight biting and percussion"] }),
  recognizedExaminationFinding({ id: "C5-EX-006", name: "recognized-no-abscess-findings", title: "Recognized No Swelling or Purulence", acceptedConcepts: ["no swelling", "no fluctuance", "no purulence", "no abscess"] }),
  recognizedExaminationFinding({ id: "C5-EX-007", name: "recognized-normal-airway-findings", title: "Recognized Normal Airway-Related Findings", acceptedConcepts: ["soft floor of mouth", "midline uvula", "normal voice", "no drooling", "patent airway"] }),
];

export const facultyRubrics = [
  {
    caseId: "case-01",
    title: "Ludwig's Angina with Impending Airway Compromise",
    criteria: case01Criteria,
  },
  {
    caseId: "case-02",
    title: "Upper-Right Odontogenic Abscess with Cellulitis and Systemic Infection",
    criteria: case02Criteria,
  },
  {
    caseId: "case-03",
    title: "Periodontal Swelling in a Patient with Diabetes",
    criteria: case03Criteria,
  },
  {
    caseId: "case-04",
    title: "Pain When Biting After a Large Restoration",
    criteria: case04Criteria,
  },
  {
    caseId: "case-05",
    title: "Symptomatic Irreversible Pulpitis of the Left Mandibular First Molar",
    criteria: case05Criteria,
  },
] satisfies FacultyRubric[];
